services:
  mother-api:
    image: python:3.11-slim
    working_dir: /app
    volumes: ["../:/app"]
    command: bash -lc "pip install -e . && uvicorn mother.api:app --host 0.0.0.0 --port 8000"
    environment:
      - MOTHER_MODEL_ENDPOINT=${MOTHER_MODEL_ENDPOINT}
      - MOTHER_DB_DSN=${MOTHER_DB_DSN}
    ports: ["8000:8000"]
  mother-worker:
    image: python:3.11-slim
    working_dir: /app
    volumes: ["../:/app"]
    command: bash -lc "pip install -e . && python -c 'import time; print("worker online"); time.sleep(360000)'"
    environment:
      - MOTHER_MODEL_ENDPOINT=${MOTHER_MODEL_ENDPOINT}
      - MOTHER_DB_DSN=${MOTHER_DB_DSN}
